routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();
Route::group(['middleware' => 'auth', 'prefix' => '/admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () {
    Route::get('post/data', 'PostController@data')->name('post.data');
    Route::resource('post', 'PostController');

    Route::get('category/data', 'CategoryController@data')->name('category.data');
    Route::resource('category', 'CategoryController');

    Route::get('page/data', 'PageController@data')->name('page.data');
    Route::resource('page', 'PageController');

    Route::get('brand/data', 'BrandController@data')->name('brand.data');
    Route::resource('brand', 'BrandController');

    Route::get('product/data', 'ProductController@data')->name('product.data');
    Route::post('product/upload-file', 'ProductController@uploadFile')->name('product.uploadFile');
    Route::post('product/delete-file', 'ProductController@deleteFile')->name('product.deleteFile');
    Route::get('product/delete/{id}', 'ProductController@delete')->name('product.delete');
    Route::resource('product', 'ProductController');


    Route::get('sim/data', 'SimController@data')->name('sim.data');
    Route::get('sim/delete/{id}', 'SimController@delete')->name('sim.delete');
    Route::resource('sim', 'SimController');

    Route::get('smartphone/data', 'SmartPhoneController@data')->name('smartphone.data');
    Route::get('smartphone/delete/{id}', 'SmartPhoneController@delete')->name('smartphone.delete');
    Route::resource('smartphone', 'SmartPhoneController');

    Route::get('locate/data', 'LocateController@data')->name('locate.data');
    Route::get('locate/delete/{id}', 'LocateController@delete')->name('locate.delete');
    Route::resource('locate', 'LocateController');

    Route::get('bank/data', 'BankController@data')->name('bank.data');
    Route::resource('bank', 'BankController');

    Route::get('banner/data', 'BannerController@data')->name('banner.data');
    Route::resource('banner', 'BannerController');

    Route::get('contact/data', 'ContactController@data')->name('contact.data');
    Route::resource('contact', 'ContactController');

    Route::get('bill/data', 'BillController@data')->name('bill.data');
    Route::resource('bill', 'BillController');

    Route::get('member/data', 'MemberController@data')->name('member.data');
    Route::resource('member', 'MemberController');
    Route::get('user/data', 'UserController@data')->name('user.data');
    Route::get('user/change-password', 'UserController@changePassword')->name('user.changePassword');
    Route::post('user/change-password', 'UserController@postChangePassword')->name('user.post.changePassword');
    Route::resource('user', 'UserController');
});

app/Http/Controllers/Admin/BillController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Entities\Bank;
use App\Entities\Bill;
use App\Http\Requests\Bank\CreateRequest;
use App\Http\Requests\Bank\UpdateRequest;
use App\Repositories\BankRepositoryEloquent;
use App\Http\Controllers\Controller;
use App\Repositories\BillRepositoryEloquent;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;
use DataTables;

class BillController extends Controller
{
    public function index()
    {
        return view('admin.bills.index');
    }

    public function data()
    {
        $data = Bill::select('*')->orderBy('id', 'desc');
        return DataTables::of($data)
            ->editColumn('member_id', function ($data) {
                return $data->member->name ?? "Không xác định";
            })
            ->editColumn('status', function ($data) {
                return $data->status == 1 ? "Đã xử lý" : "Chờ xử lý";
            })
            ->editColumn('product_id', function ($data) {
                return $data->product->name ?? 'Không xác định';
            })
            ->editColumn('price', function ($data) {
                return number_format($data->price, 0, '', ',');
            })
            ->editColumn('created_at', function ($data) {
                return $data->created_at->format("d/m/Y H:i:s");
            })
            ->addColumn('action', function ($data) {
                return '<form action="' . route('admin.bill.destroy', $data->id) . '" method="post">' .
                    method_field('DELETE') . csrf_field() . '
                            <a href="' . route('admin.bill.show', $data->id) . '" class="btn btn-xs btn-warning"><i class="fa fa-eye"></i> Chi tiết</a>
                            <button type="submit" class="btn btn-xs btn-danger btn-delete"><i class="fa fa-times"></i> Delete</button>
                        </form>';
            })
            ->rawColumns(['action'])
            ->make(true);
    }

    public function show($id, BillRepositoryEloquent $billRepository)
    {
        $data['bill'] = $billRepository->find($id);
        return view('admin.bills.show', $data);
    }

    public function update($id, Request $request, BillRepositoryEloquent $billRepository)
    {
        $bill = $billRepository->find($id);
        $data = $request->only(['status']);
        $update = $bill->update($data);
        if ($update) {
            Alert::success('Cập nhật thành công');
            return redirect()->route('admin.bill.index');
        }
        Alert::error('Cập nhật thất bại');
        return back();
    }

    public function destroy($id, BillRepositoryEloquent $billRepository)
    {
        try {
            $billRepository->delete($id);
            Alert::success('Xóa thành công!');
            return redirect()->back();
        } catch (\Exception $exception) {
            Alert::success('Xóa Thất bại!');
            return redirect()->back();
        }

    }
}

app/Http/Controllers/Api/BillController.php
<?php

namespace App\Http\Controllers\Api;

use App\Entities\Product;
use App\Http\Controllers\Controller;
use App\Http\Requests\Api\Bill\AddBillRequest;
use App\Repositories\BillRepositoryEloquent;
use App\Repositories\ProductRepositoryEloquent;
use Illuminate\Http\Response;

class BillController extends Controller
{
    public function addBill(AddBillRequest $request, BillRepositoryEloquent $billRepository, ProductRepositoryEloquent $productRepository)
    {
        $member = auth('api')->user();
        if (is_object($member)) {
            $product = Product::find($request->get('product_id'));
            if (is_object($product)){
                $billCheck = $billRepository->findWhere(['member_id' => $member->id, 'product_id' => $product->id, 'status' => 0])->first();
                if (!is_object($billCheck)) {
                    $bill = $billRepository->create(array_merge(['member_id' => $member->id, 'product_id' => $product->id, 'price' => $product->price, 'status' => 0], $request->only(['email', 'phone', 'address', 'content'])));
                    if (is_object($bill)) {
                        $bill->member;
                        return response()->json([
                            'status' => true,
                            'msg' => 'Mua hàng thành công!',
                            'data' => $bill
                        ], Response::HTTP_OK);
                    } else {
                        return response()->json([
                            'status' => false,
                            'msg' => 'Mua hàng thất bại!!'
                        ], Response::HTTP_BAD_REQUEST);
                    }
                } else {
                    return response()->json([
                        'status' => false,
                        'msg' => 'Bạn đã mua sản phẩm này rồi! Vui lòng đợi chúng tôi xử lý!'
                    ], Response::HTTP_CREATED);
                }
            }else{
                return response()->json([
                    'status' => false,
                    'msg' => 'Sản phẩm không tồn tại!'
                ], Response::HTTP_FORBIDDEN);
            }

        }
        return response()->json([
            'status' => false,
            'msg' => 'Bạn chưa đăng nhập!'
        ], Response::HTTP_FORBIDDEN);
    }

    public function listBill(BillRepositoryEloquent $billRepository)
    {
        try {
            $member = auth('api')->user();
            if (is_object($member)) {
                $bills = $member->bills()->with('product')->get();
                return response()->json([
                    'status' => true,
                    'msg' => 'Danh sách đơn hàng của bạn!',
                    'data' => $bills
                ], Response::HTTP_OK);
            }
            return response()->json([
                'status' => false,
                'msg' => 'Bạn chưa đăng nhập!'
            ], Response::HTTP_FORBIDDEN);
        } catch (\Exception $exception) {
            return response()->json([
                'status' => false,
                'msg' => 'Lỗi! Vui lòng liên hệ quản trị!'
            ], Response::HTTP_BAD_REQUEST);
        }

    }
}

resources/views/admin/bills/index.blade.php
@extends('admin.layouts.master')
@section('css')
    <link href="{{ URL::asset('assets/plugins/datatable/dataTables.bootstrap4.min.css')}}" rel="stylesheet">
    <link href="{{ URL::asset('assets/plugins/select2/select2.min.css')}}" rel="stylesheet">
    <link href="{{ URL::asset('assets/plugins/sweet-alert/sweetalert.css')}}" rel="stylesheet">
@endsection
@section('page-header')
    <!-- PAGE-HEADER -->
    <div>
        <h1 class="page-title">Danh sách đơn hàng</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Admin</a></li>
            <li class="breadcrumb-item active" aria-current="page">Danh sách đơn hàng</li>
        </ol>
    </div>
    <!-- PAGE-HEADER END -->
@endsection
@section('content')
    <!-- ROW-1 OPEN -->
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="card">
                <div class="card-header ">
                    <div class="text-right col-md-12">
                        <a href="{{route('admin.bill.create')}}" class="btn btn-primary">Thêm mới</a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="category-table" class="table table-striped table-bordered text-nowrap w-100">
                            <thead>
                            <tr>
                                <th class="wd-15p">ID</th>
                                <th class="wd-15p">Khách hàng</th>
                                <th class="wd-15p">Email</th>
                                <th class="wd-15p">Số điện thoại</th>
                                <th class="wd-15p">Sản phẩm</th>
                                <th class="wd-15p">Giá</th>
                                <th class="wd-15p">Địa chỉ</th>
                                <th class="wd-15p">Ngày đặt</th>
                                <th class="wd-15p">Ghi chú</th>
                                <th class="wd-15p">Trạng thái</th>
                                <th class="wd-15p">Hành động</th>
                            </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- TABLE WRAPPER -->
            </div>
            <!-- SECTION WRAPPER -->
        </div>
    </div>
    <!-- ROW-1 CLOSED -->

    </div>
    </div>
    <!-- CONTAINER CLOSED -->
    </div>
@endsection
@section('js')
    <script src="{{ URL::asset('assets/plugins/datatable/jquery.dataTables.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/dataTables.responsive.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/sweet-alert/sweetalert.min.js') }}"></script>
    <script src="{{ URL::asset('assets/js/sweet-alert.js') }}"></script>
    <script src="{{ URL::asset('assets/js/popover.js') }}"></script>
    <script>
        $(function() {
            $('#category-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{{ route('admin.bill.data') }}',
                columns: [
                    { data: 'id', name: 'id' },
                    { data: 'member_id', name: 'member_id' },
                    { data: 'email', name: 'email' },
                    { data: 'phone', name: 'phone' },
                    { data: 'product_id', name: 'product_id' },
                    { data: 'price', name: 'price' },
                    { data: 'address', name: 'address' },
                    { data: 'created_at', name: 'created_at' },
                    { data: 'content', name: 'content' },
                    { data: 'status', name: 'status' },
                    { data: 'action', name: 'action' },
                ]
            });
        });
    </script>
@endsection

resources/views/admin/bills/show.blade.php
@extends('admin.layouts.master')
@section('css')
    <link href="{{ URL::asset('assets/plugins/bootstrap-daterangepicker/daterangepicker.css')}}" rel="stylesheet"/>
    <link href="{{ URL::asset('assets/plugins/date-picker/spectrum.css')}}" rel="stylesheet"/>
    <link href="{{ URL::asset('assets/plugins/fileuploads/css/fileupload.css')}}" rel="stylesheet"/>
    <link href="{{ URL::asset('assets/plugins/multipleselect/multiple-select.css')}}" rel="stylesheet"/>
    <link href="{{ URL::asset('assets/plugins/select2/select2.min.css')}}" rel="stylesheet"/>
    <link href="{{ URL::asset('assets/plugins/time-picker/jquery.timepicker.css')}}" rel="stylesheet"/>
@endsection
@section('page-header')
    <!-- PAGE-HEADER -->
    <div>
        <h1 class="page-title">Chi tiết đơn hàng</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Admin</a></li>
            <li class="breadcrumb-item"><a href="{{route('admin.bill.index')}}">Đơn hàng</a></li>
            <li class="breadcrumb-item active" aria-current="page">Chi tiết</li>
        </ol>
    </div>
    <!-- PAGE-HEADER END -->
@endsection
@section('content')
    <!-- ROW-1 OPEN -->
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="card">
                <form action="{{route('admin.bill.update',$bill->id)}}" method="post">
                    @csrf
                    {{ method_field('PUT') }}
                    <div class="card-header ">
                        <div class="text-right col-md-12">
                            <button class="btn btn-primary" type="submit">Lưu</button>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-9">
                                    <div class="form-group">
                                        <ul class="list-group">
                                            <li class="listunorder">Khách hàng: {{$bill->member->name??"Không xách định!"}}</li>
                                            <li class="listunorder">Email: {{$bill->email}}</li>
                                            <li class="listunorder">Số điện thoại: {{$bill->phone}}</li>
                                            <li class="listunorder">Sản phẩm: {{$bill->product->name??"Không xác định"}}</li>
                                            <li class="listunorder">Giá: {{number_format($bill->price, 0, '', ',')}}</li>
                                            <li class="listunorder">Địa chỉ: {{$bill->address}}</li>
                                            <li class="listunorder">Thời gian đặt hàng: {{$bill->created_at->format("d/m/Y H:i:s")}}</li>
                                            <li class="listunorder">Nội dung: {{$bill->content}}</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="form-label">Trạng thái</label>
                                        <select class="form-control select2" name="status">
                                            <option value=1 {{$bill->status==1?'selected':''}}>Đã xử lý</option>
                                            <option value=0 {{$bill->status==0?'selected':''}}>Chưa xử lý</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                <!-- TABLE WRAPPER -->
            </div>
            <!-- SECTION WRAPPER -->
        </div>
    </div>
    <!-- ROW-1 CLOSED -->
    <!-- CONTAINER CLOSED -->
    </div>
@endsection
@section('js')
    <script src="{{ URL::asset('assets/plugins/bootstrap-daterangepicker/moment.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/date-picker/spectrum.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/date-picker/jquery-ui.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/fileuploads/js/fileupload.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/fileuploads/js/file-upload.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/input-mask/jquery.maskedinput.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/multipleselect/multiple-select.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/multipleselect/multi-select.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/select2/select2.full.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/time-picker/jquery.timepicker.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/time-picker/toggles.min.js') }}"></script>
    <script src="{{ URL::asset('assets/js/form-elements.js') }}"></script>
@endsection

resources/views/admin/bills/update.blade.php
@extends('admin.layouts.master')
@section('css')
    <link href="{{ URL::asset('assets/plugins/bootstrap-daterangepicker/daterangepicker.css')}}" rel="stylesheet"/>
    <link href="{{ URL::asset('assets/plugins/date-picker/spectrum.css')}}" rel="stylesheet"/>
    <link href="{{ URL::asset('assets/plugins/fileuploads/css/fileupload.css')}}" rel="stylesheet"/>
    <link href="{{ URL::asset('assets/plugins/multipleselect/multiple-select.css')}}" rel="stylesheet"/>
    <link href="{{ URL::asset('assets/plugins/select2/select2.min.css')}}" rel="stylesheet"/>
    <link href="{{ URL::asset('assets/plugins/time-picker/jquery.timepicker.css')}}" rel="stylesheet"/>
@endsection
@section('page-header')
    <!-- PAGE-HEADER -->
    <div>
        <h1 class="page-title">Chỉnh sửa Ngân hàng</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Admin</a></li>
            <li class="breadcrumb-item"><a href="{{route('admin.bank.index')}}">Ngân hàng</a></li>
            <li class="breadcrumb-item active" aria-current="page">Chỉnh sửa</li>
        </ol>
    </div>
    <!-- PAGE-HEADER END -->
@endsection
@section('content')
    <!-- ROW-1 OPEN -->
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="card">
                <form action="{{route('admin.bank.update',$bank->id)}}" method="post">
                    @csrf
                    {{ method_field('PUT') }}
                    <div class="card-header ">
                        <div class="text-right col-md-12">
                            <button class="btn btn-primary" type="submit">Lưu</button>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-9">
                                    <div class="form-group">
                                        <input type="text" class="form-control" name="name" value="{{$bank->name}}"
                                               placeholder="Nhập tên ngân hàng">
                                    </div>
                                    <div class="form-group">
                                        <input type="text" class="form-control" name="account" value="{{$bank->account}}"
                                               placeholder="Nhập chủ tài khoản">
                                    </div>
                                    <div class="form-group">
                                        <input type="text" class="form-control" name="number" value="{{$bank->number}}"
                                               placeholder="Nhập số tài khoản">
                                    </div>
                                    <div class="form-group">
                                        <input type="text" class="form-control" name="branch" value="{{$bank->branch}}"
                                               placeholder="Nhập chi nhánh">
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="form-label">Trạng thái</label>
                                        <select class="form-control select2" name="status">
                                            <option value=1 {{$bank->status==1?'selected':''}}>Hoạt động</option>
                                            <option value=0 {{$bank->status==0?'selected':''}}>Tạm dừng</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                <!-- TABLE WRAPPER -->
            </div>
            <!-- SECTION WRAPPER -->
        </div>
    </div>
    <!-- ROW-1 CLOSED -->
    <!-- CONTAINER CLOSED -->
    </div>
@endsection
@section('js')
    <script src="{{ URL::asset('assets/plugins/bootstrap-daterangepicker/moment.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/date-picker/spectrum.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/date-picker/jquery-ui.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/fileuploads/js/fileupload.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/fileuploads/js/file-upload.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/input-mask/jquery.maskedinput.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/multipleselect/multiple-select.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/multipleselect/multi-select.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/select2/select2.full.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/time-picker/jquery.timepicker.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/time-picker/toggles.min.js') }}"></script>
    <script src="{{ URL::asset('assets/js/form-elements.js') }}"></script>
@endsection