routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();
Route::group(['middleware' => 'auth', 'prefix' => '/admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () {
    Route::get('post/data', 'PostController@data')->name('post.data');
    Route::resource('post', 'PostController');

    Route::get('category/data', 'CategoryController@data')->name('category.data');
    Route::resource('category', 'CategoryController');

    Route::get('page/data', 'PageController@data')->name('page.data');
    Route::resource('page', 'PageController');

    Route::get('brand/data', 'BrandController@data')->name('brand.data');
    Route::resource('brand', 'BrandController');

    Route::get('product/data', 'ProductController@data')->name('product.data');
    Route::post('product/upload-file', 'ProductController@uploadFile')->name('product.uploadFile');
    Route::post('product/delete-file', 'ProductController@deleteFile')->name('product.deleteFile');
    Route::get('product/delete/{id}', 'ProductController@delete')->name('product.delete');
    Route::resource('product', 'ProductController');


    Route::get('sim/data', 'SimController@data')->name('sim.data');
    Route::get('sim/delete/{id}', 'SimController@delete')->name('sim.delete');
    Route::resource('sim', 'SimController');

    Route::get('smartphone/data', 'SmartPhoneController@data')->name('smartphone.data');
    Route::get('smartphone/delete/{id}', 'SmartPhoneController@delete')->name('smartphone.delete');
    Route::resource('smartphone', 'SmartPhoneController');

    Route::get('locate/data', 'LocateController@data')->name('locate.data');
    Route::get('locate/delete/{id}', 'LocateController@delete')->name('locate.delete');
    Route::resource('locate', 'LocateController');

    Route::get('bank/data', 'BankController@data')->name('bank.data');
    Route::resource('bank', 'BankController');

    Route::get('banner/data', 'BannerController@data')->name('banner.data');
    Route::resource('banner', 'BannerController');

    Route::get('contact/data', 'ContactController@data')->name('contact.data');
    Route::resource('contact', 'ContactController');

    Route::get('bill/data', 'BillController@data')->name('bill.data');
    Route::resource('bill', 'BillController');

    Route::get('member/data', 'MemberController@data')->name('member.data');
    Route::resource('member', 'MemberController');
    Route::get('user/data', 'UserController@data')->name('user.data');
    Route::get('user/change-password', 'UserController@changePassword')->name('user.changePassword');
    Route::post('user/change-password', 'UserController@postChangePassword')->name('user.post.changePassword');
    Route::resource('user', 'UserController');
});

app/Http/Controllers/Admin/MemberController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Entities\Member;
use App\Http\Controllers\Controller;
use App\Http\Requests\Member\CreateRequest;
use App\Http\Requests\Member\UpdateRequest;
use App\Repositories\MemberRepositoryEloquent;
use Illuminate\Support\Facades\Storage;
use RealRashid\SweetAlert\Facades\Alert;
use DataTables;

class MemberController extends Controller
{
    public function index()
    {
        return view('admin.members.index');
    }

    public function data()
    {
        $data = Member::select('*')->orderBy('id', 'desc');
        return DataTables::of($data)
            ->editColumn('avatar', function ($data) {
                return '<img src="' . $data->avatar . '" width="150px">';
            })
            ->editColumn('status', function ($data) {
                return $data->status == 1 ? "Hoạt động" : "Tạm dừng";
            })
            ->addColumn('action', function ($data) {
                return '
                        <form action="' . route('admin.member.destroy', $data->id) . '" method="post">' .
                    method_field('DELETE') . csrf_field() . '
                            <a href="' . route('admin.member.edit', $data->id) . '" class="btn btn-xs btn-warning"><i class="fa fa-eye"></i> Edit</a>
                            <button type="submit" class="btn btn-xs btn-danger btn-delete"><i class="fa fa-times"></i> Delete</button>
                        </form>';
            })
            ->rawColumns(['avatar', 'action'])
            ->make(true);
    }

    public function create(MemberRepositoryEloquent $memberRepository)
    {
        return view('admin.members.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateRequest $request
     * @param MemberRepositoryEloquent $memberRepository
     * @return void
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function store(CreateRequest $request, MemberRepositoryEloquent $memberRepository)
    {
        $data = array_merge(['password' => bcrypt($request->get('password'))], $request->only(['name', 'user_name', 'email', 'address', 'description', 'status', 'phone']));
        if ($request->hasFile('avatar')) {
            $file = $request->file('avatar')->store('public/members');
            $url = Storage::url($file);
            $data['avatar'] = asset($url);
        }
        if ($request->hasFile('cover_image')) {
            $file = $request->file('cover_image')->store('public/members');
            $url = Storage::url($file);
            $data['cover_image'] = asset($url);
        }
        $brand = $memberRepository->create($data);
        if ($brand) {
            Alert::success('Thêm mới thành công');
            return redirect()->route('admin.member.index');
        }
        Alert::error('Thêm mới Thất bại');
        return redirect()->back();
    }


    public function edit($id, MemberRepositoryEloquent $memberRepository)
    {
        $data['member'] = $memberRepository->find($id);
        return view('admin.members.update', $data);
    }

    public function update($id, UpdateRequest $request, MemberRepositoryEloquent $memberRepository)
    {
        $member = $memberRepository->find($id);
        $data = $request->only(['name', 'user_name', 'email', 'address', 'description', 'status', 'phone']);
        if ($request->hasFile('avatar')) {
            $file = $request->file('avatar')->store('public/members');
            $url = Storage::url($file);
            $data['avatar'] = asset($url);
        }
        if ($request->hasFile('cover_image')) {
            $file = $request->file('cover_image')->store('public/members');
            $url = Storage::url($file);
            $data['cover_image'] = asset($url);
        }
        $update = $member->update($data);
        if ($update) {
            Alert::success('Cập nhật thành công');
            return redirect()->route('admin.member.index');
        }
        Alert::error('Cập nhật thất bại');
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $id
     * @param MemberRepositoryEloquent $memberRepository
     * @return \Illuminate\Http\Response
     */
    public function destroy($id, MemberRepositoryEloquent $memberRepository)
    {
        try {
            $memberRepository->delete($id);
            Alert::success('Xóa thành công!');
            return redirect()->back();
        } catch (\Exception $exception) {
            Alert::success('Xóa Thất bại!');
            return redirect()->back();
        }

    }
}

resources/views/admin/members/add.blade.php
@extends('admin.layouts.master')
@section('css')
    <link href="{{ URL::asset('assets/plugins/bootstrap-daterangepicker/daterangepicker.css')}}" rel="stylesheet"/>
    <link href="{{ URL::asset('assets/plugins/date-picker/spectrum.css')}}" rel="stylesheet"/>
    <link href="{{ URL::asset('assets/plugins/fileuploads/css/fileupload.css')}}" rel="stylesheet"/>
    <link href="{{ URL::asset('assets/plugins/multipleselect/multiple-select.css')}}" rel="stylesheet"/>
    <link href="{{ URL::asset('assets/plugins/select2/select2.min.css')}}" rel="stylesheet"/>
    <link href="{{ URL::asset('assets/plugins/time-picker/jquery.timepicker.css')}}" rel="stylesheet"/>
@endsection
@section('page-header')
    <!-- PAGE-HEADER -->
    <div>
        <h1 class="page-title">Thêm mới khách hàng</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Admin</a></li>
            <li class="breadcrumb-item"><a href="{{route('admin.member.index')}}">Khách hàng</a></li>
            <li class="breadcrumb-item active" aria-current="page">Thêm mới</li>
        </ol>
    </div>
    <!-- PAGE-HEADER END -->
@endsection
@section('content')
    <!-- ROW-1 OPEN -->
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="card">
                <form action="{{route('admin.member.store')}}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="card-header ">
                        <div class="text-right col-md-12">
                            <button class="btn btn-primary" type="submit">Lưu</button>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-9">
                                    <div class="form-group">
                                        <label class="form-label">Tên khách hàng</label>
                                        <input type="text" class="form-control" name="name"
                                               placeholder="Nhập tên khách hàng">
                                        @error('name')
                                        <div class="alert alert-warning" role="alert">
                                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>{{ $message }}
                                        </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label">Tên tài khoản</label>
                                        <input type="text" class="form-control" name="user_name" required
                                               placeholder="Nhập Tên tài khoản">
                                        @error('user_name')
                                        <div class="alert alert-warning" role="alert">
                                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>{{ $message }}
                                        </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label">Email</label>
                                        <input type="text" class="form-control" name="email"
                                               placeholder="Nhập email">
                                        @error('email')
                                        <div class="alert alert-warning" role="alert">
                                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>{{ $message }}
                                        </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label">Số điện thoại</label>
                                        <input type="text" class="form-control" name="phone"
                                               placeholder="Nhập Số điện thoại">
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label">Mô tả ngắn</label>
                                        <input type="text" class="form-control" name="description"
                                               placeholder="Nhập mô tả ngắn">
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label">Địa chỉ</label>
                                        <input type="text" class="form-control" name="address"
                                               placeholder="Nhập địa chỉ">
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label">Mật khẩu</label>
                                        <input type="text" class="form-control" name="password"
                                               placeholder="Nhập mật khẩu">
                                        @error('password')
                                        <div class="alert alert-warning" role="alert">
                                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>{{ $message }}
                                        </div>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="form-label">Trạng thái</label>
                                        <select class="form-control select2" name="status">
                                            <option value=1>Hoạt động</option>
                                            <option value=0>Tạm dừng</option>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label">Ảnh đại diện</label>
                                        <input type="file" name="avatar"
                                               class="dropify"/>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label">Ảnh bìa</label>
                                        <input type="file" name="cover_image"
                                               class="dropify_cover_image"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                <!-- TABLE WRAPPER -->
            </div>
            <!-- SECTION WRAPPER -->
        </div>
    </div>
    <!-- ROW-1 CLOSED -->

    <!-- CONTAINER CLOSED -->
    </div>
@endsection
@section('js')
    <script src="{{ URL::asset('assets/plugins/bootstrap-daterangepicker/moment.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/date-picker/spectrum.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/date-picker/jquery-ui.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/fileuploads/js/fileupload.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/fileuploads/js/file-upload.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/input-mask/jquery.maskedinput.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/multipleselect/multiple-select.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/multipleselect/multi-select.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/select2/select2.full.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/time-picker/jquery.timepicker.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/time-picker/toggles.min.js') }}"></script>
    <script src="{{ URL::asset('assets/js/form-elements.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('.dropify_cover_image').dropify();
        });
    </script>
@endsection

resources/views/admin/members/index.blade.php
@extends('admin.layouts.master')
@section('css')
    <link href="{{ URL::asset('assets/plugins/datatable/dataTables.bootstrap4.min.css')}}" rel="stylesheet">
    <link href="{{ URL::asset('assets/plugins/select2/select2.min.css')}}" rel="stylesheet">
    <link href="{{ URL::asset('assets/plugins/sweet-alert/sweetalert.css')}}" rel="stylesheet">
@endsection
@section('page-header')
    <!-- PAGE-HEADER -->
    <div>
        <h1 class="page-title">Danh sách khách hàng</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Admin</a></li>
            <li class="breadcrumb-item active" aria-current="page">Danh sách khách hàng</li>
        </ol>
    </div>
    <!-- PAGE-HEADER END -->
@endsection
@section('content')
    <!-- ROW-1 OPEN -->
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="card">
                <div class="card-header ">
                    <div class="text-right col-md-12">
                        <a href="{{route('admin.member.create')}}" class="btn btn-primary">Thêm mới</a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="member-table" class="table table-striped table-bordered text-nowrap w-100">
                            <thead>
                            <tr>
                                <th class="wd-15p">ID</th>
                                <th class="wd-15p">Ảnh</th>
                                <th class="wd-15p">Tài khoản</th>
                                <th class="wd-15p">Tên</th>
                                <th class="wd-15p">Email</th>
                                <th class="wd-15p">Số điện thoại</th>
                                <th class="wd-15p">Địa chỉ</th>
                                <th class="wd-15p">Trạng thái</th>
                                <th class="wd-15p">Hành động</th>
                            </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- TABLE WRAPPER -->
            </div>
            <!-- SECTION WRAPPER -->
        </div>
    </div>
    <!-- ROW-1 CLOSED -->

    </div>
    </div>
    <!-- CONTAINER CLOSED -->
    </div>
@endsection
@section('js')
    <script src="{{ URL::asset('assets/plugins/datatable/jquery.dataTables.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/dataTables.responsive.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/sweet-alert/sweetalert.min.js') }}"></script>
    <script src="{{ URL::asset('assets/js/sweet-alert.js') }}"></script>
    <script src="{{ URL::asset('assets/js/popover.js') }}"></script>
    <script>
        $(function() {
            $('#member-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{{ route('admin.member.data') }}',
                columns: [
                    { data: 'id', name: 'id' },
                    { data: 'avatar', name: 'avatar' },
                    { data: 'user_name', name: 'user_name' },
                    { data: 'name', name: 'name' },
                    { data: 'email', name: 'email' },
                    { data: 'phone', name: 'phone' },
                    { data: 'address', name: 'address' },
                    { data: 'status', name: 'status' },
                    { data: 'action', name: 'action' },
                ]
            });
        });
    </script>
@endsection

resources/views/admin/members/update.blade.php
@extends('admin.layouts.master')
@section('css')
    <link href="{{ URL::asset('assets/plugins/bootstrap-daterangepicker/daterangepicker.css')}}" rel="stylesheet"/>
    <link href="{{ URL::asset('assets/plugins/date-picker/spectrum.css')}}" rel="stylesheet"/>
    <link href="{{ URL::asset('assets/plugins/fileuploads/css/fileupload.css')}}" rel="stylesheet"/>
    <link href="{{ URL::asset('assets/plugins/multipleselect/multiple-select.css')}}" rel="stylesheet"/>
    <link href="{{ URL::asset('assets/plugins/select2/select2.min.css')}}" rel="stylesheet"/>
    <link href="{{ URL::asset('assets/plugins/time-picker/jquery.timepicker.css')}}" rel="stylesheet"/>
@endsection
@section('page-header')
    <!-- PAGE-HEADER -->
    <div>
        <h1 class="page-title">Chỉnh sửa khách hàng</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Admin</a></li>
            <li class="breadcrumb-item"><a href="{{route('admin.member.index')}}">Khách hàng</a></li>
            <li class="breadcrumb-item active" aria-current="page">Chỉnh sửa</li>
        </ol>
    </div>
    <!-- PAGE-HEADER END -->
@endsection
@section('content')
    <!-- ROW-1 OPEN -->
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="card">
                <form action="{{route('admin.member.update',$member->id)}}" method="post" enctype="multipart/form-data">
                    @csrf
                    {{ method_field('PUT') }}
                    <div class="card-header">
                        <div class="text-right col-md-12">
                            <button class="btn btn-primary" type="submit">Lưu</button>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-9">
                                    <div class="form-group">
                                        <label class="form-label">Tên khách hàng</label>
                                        <input type="text" class="form-control" name="name" value="{{$member->name}}"
                                               placeholder="Nhập tên khách hàng">
                                        @error('name')
                                        <div class="alert alert-warning" role="alert">
                                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>{{ $message }}
                                        </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label">Tên tài khoản</label>
                                        <input type="text" class="form-control" name="user_name" value="{{$member->user_name}}"
                                               placeholder="Nhập Tên tài khoản" required>
                                        @error('user_name')
                                        <div class="alert alert-warning" role="alert">
                                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>{{ $message }}
                                        </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label">Email</label>
                                        <input type="text" class="form-control" name="email" value="{{$member->email}}"
                                               placeholder="Nhập email ">
                                        @error('email')
                                        <div class="alert alert-warning" role="alert">
                                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>{{ $message }}
                                        </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label">Số điện thoại</label>
                                        <input type="text" class="form-control" name="phone" value="{{$member->phone}}"
                                               placeholder="Nhập Số điện thoại">
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label">Mô tả ngắn</label>
                                        <input type="text" class="form-control" name="description" value="{{$member->description}}"
                                               placeholder="Nhập mô tả ngắn">
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label">Mật khẩu</label>
                                        <input type="text" class="form-control" name="address" value="{{$member->address}}"
                                               placeholder="Nhập địa chỉ">
                                        @error('password')
                                        <div class="alert alert-warning" role="alert">
                                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>{{ $message }}
                                        </div>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="form-label">Trạng thái</label>
                                        <select class="form-control select2" name="status">
                                            <option value=1 {{$member->status==1?'selected':''}}>Hoạt động</option>
                                            <option value=0 {{$member->status==0?'selected':''}}>Tạm dừng</option>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label">Ảnh đại diện</label>
                                        <input type="file" name="avatar" data-default-file="{{$member->avatar}}"
                                               class="dropify"/>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label">Ảnh bìa</label>
                                        <input type="file" name="cover_image" data-default-file="{{$member->cover_image}}"
                                               class="dropify_cover_image"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                <!-- TABLE WRAPPER -->
            </div>
            <!-- SECTION WRAPPER -->
        </div>
    </div>
    <!-- ROW-1 CLOSED -->
    <!-- CONTAINER CLOSED -->
    </div>
@endsection
@section('js')
    <script src="{{ URL::asset('assets/plugins/bootstrap-daterangepicker/moment.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/date-picker/spectrum.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/date-picker/jquery-ui.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/fileuploads/js/fileupload.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/fileuploads/js/file-upload.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/input-mask/jquery.maskedinput.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/multipleselect/multiple-select.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/multipleselect/multi-select.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/select2/select2.full.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/time-picker/jquery.timepicker.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/time-picker/toggles.min.js') }}"></script>
    <script src="{{ URL::asset('assets/js/form-elements.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('.dropify_cover_image').dropify();
        });
    </script>
@endsection